name: Test package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ '7.3', '7.4', '8.0', '8.1' ]
        stability: [ prefer-lowest, prefer-stable ]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        ini-values: xdebug.mode="coverage"
        coverage: xdebug

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Require Swagger PHP
      run: composer require 'zircote/swagger-php:3.*' --no-interaction --no-update
      if: matrix.php < 8

    - name: Prepare enviroment
      run: |
        sudo chown -R $USER:$USER .
        sudo chmod -R g+rw .
        mkdir -p tests/storage/logs/test-reports
        mkdir -p vendor/orchestra/testbench-core/laravel/vendor/swagger-api
        mkdir -p vendor/orchestra/testbench-core/laravel/vendor/swagger-api/swagger-ui
        mkdir -p vendor/orchestra/testbench-core/laravel/vendor/swagger-api/swagger-ui/dist
        sudo chown -R $USER:$USER vendor/orchestra/testbench-core/laravel/vendor/swagger-api
        chmod -R 777 vendor/orchestra/testbench-core/laravel/vendor/swagger-api

    - name: Run test suite
      run: composer run-script phpunit

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: d5b1b36d663604a8900fb8a586625a94eae6cdb6f6d7372aec8f066c174b4a5c
      with:
        coverageLocations: ${{github.workspace}}/tests/storage/logs/test-reports/clover.xml
      if: matrix.php == '8.0'
